# 3474. Lexicographically Smallest Generated String

# You are given two strings, str1 and str2, of lengths n and m, respectively.

# A string word of length n + m - 1 is defined to be generated by str1 and str2 if it satisfies the following conditions for each index 0 <= i <= n - 1:

# If str1[i] == 'T', the substring of word with size m starting at index i is equal to str2, i.e., word[i..(i + m - 1)] == str2.
# If str1[i] == 'F', the substring of word with size m starting at index i is not equal to str2, i.e., word[i..(i + m - 1)] != str2.
# Return the lexicographically smallest possible string that can be generated by str1 and str2. If no string can be generated, return an empty string "".

 

# Example 1:

# Input: str1 = "TFTF", str2 = "ab"

# Output: "ababa"

# Explanation:

# The table below represents the string "ababa"
# Index	T/F	Substring of length m
# 0	'T'	"ab"
# 1	'F'	"ba"
# 2	'T'	"ab"
# 3	'F'	"ba"
# The strings "ababa" and "ababb" can be generated by str1 and str2.

# Return "ababa" since it is the lexicographically smaller string.

# Example 2:

# Input: str1 = "TFTF", str2 = "abc"

# Output: ""

# Explanation:

# No string that satisfies the conditions can be generated.

# Example 3:

# Input: str1 = "F", str2 = "d"

# Output: "a"

 

# Constraints:

# 1 <= n == str1.length <= 10^4
# 1 <= m == str2.length <= 500
# str1 consists only of 'T' or 'F'.
# str2 consists only of lowercase English characters.


# Solution:



class Solution(object):
    def generateString(self, str1, str2):
        """
        :type str1: str
        :type str2: str
        :rtype: str
        """
        n, m = len(str1), len(str2)
        ans = ['?'] * (n + m - 1)  # ? indicates a pending position
        
        # Process 'T'
        for i, b in enumerate(str1):
            if b != 'T':
                continue
            # The substring must match str2
            for j, c in enumerate(str2):
                v = ans[i + j]
                if v != '?' and v != c:
                    return ""
                ans[i + j] = c
        
        old_ans = ans[:]
        ans = ['a' if c == '?' else c for c in ans]  # Default fill
        
        # Process 'F'
        for i, b in enumerate(str1):
            if b != 'F':
                continue
            # Substring must not equal str2
            if ''.join(ans[i: i + m]) != str2:
                continue
            # Find a position to tweak
            for j in range(i + m - 1, i - 1, -1):
                if old_ans[j] == '?':
                    ans[j] = 'b'
                    break
            else:
                return ""
        
        return ''.join(ans)